ToDoApplication/ToDoApplication/Models/BaseModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ToDoApplication.Models
{
    public class BaseModel
    {
        public int Id { get; set; }
    }
}

ToDoApplication/ToDoApplication/Models/Category.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ToDoApplication.Models
{
    public class Category : BaseModel
    {
        public string Name { get; set; }

        public virtual List<Todo> Todoes { get; set; }
    }
}

ToDoApplication/ToDoApplication/Models/Todo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ToDoApplication.Models
{
    public class Todo : BaseModel
    {
        public int CategoryId { get; set; }
        public string Title { get; set; }
        public bool IsDone { get; set; }

        public virtual Category Category { get; set; }
    }
}

ToDoApplication/ToDoApplication/ViewModels/Category/CategoryCreateViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ToDoApplication.ViewModels.Category
{
    public class CategoryCreateViewModel
    {
        public int Id { get; set; }

        [Required]
        [RegularExpression("[A-Za-z]+", ErrorMessage = "Name should contain letters only")]
        public string Name { get; set; }
    }
}

ToDoApplication/ToDoApplication/ViewModels/Category/CategoryEditViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace ToDoApplication.ViewModels.Category
{
    public class CategoryEditViewModel
    {
        public int Id { get; set; }

        [Required]
        [RegularExpression("[A-Za-z]+", ErrorMessage = "Name should contain letters only")]
        public string Name { get; set; }

    }
}

ToDoApplication/ToDoApplication/ViewModels/Category/CategoryIndexViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using ToDoApplication;

namespace ToDoApplication.ViewModels.Category
{
    public class CategoryIndexViewModel
    {
        public DateTime CurrentDateTime { get; set; }
        public List<Models.Category> Categories { get; set; }
    }
}

ToDoApplication/ToDoApplication/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Configuration;
using ToDoApplication.EfDataAccess;
using ToDoApplication.Models;
using ToDoApplication.ViewModels.Category;

namespace ToDoApplication.Controllers
{
    public class CategoryController : Controller
    {
        //
        // GET: /Category/
        public ActionResult Index()
        {
            CategoryIndexViewModel model = new CategoryIndexViewModel();

            CategoryRepository repository = new CategoryRepository();

            model.CurrentDateTime = DateTime.Now;
            model.Categories = repository.GetAll();

            return View(model);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(CategoryCreateViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            CategoryRepository repository = new CategoryRepository();

            Category category = new Category();
            category.Id = model.Id;
            category.Name = model.Name;

            repository.Save(category);

            return RedirectToAction("Index");
        }

        public ActionResult Edit(int id)
        {
            CategoryRepository repository = new CategoryRepository();

            Category category = repository.Get(id);

            if (category == null)
            {
                return HttpNotFound();
            }

            CategoryEditViewModel model = new CategoryEditViewModel();
            model.Id = category.Id;
            model.Name = category.Name;

            return View(model);            
        }

        [HttpPost]
        public ActionResult Edit(CategoryEditViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            CategoryRepository repository = new CategoryRepository();

            Category category = repository.Get(model.Id);

            if (category == null)
            {
                return HttpNotFound();
            }

            category.Id = model.Id;
            category.Name = model.Name;

            repository.Save(category);


            return RedirectToAction("Index");
        }
        public ActionResult Delete(int id)
        {
            CategoryRepository repository = new CategoryRepository();

            Category category = repository.Get(id);
            if (category == null)
            {
                return HttpNotFound();
            }

            repository.Delete(category);

            return RedirectToAction("Index");
        }
	}
}

ToDoApplication/ToDoApplication/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ToDoApplication.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

ToDoApplication/ToDoApplication/Controllers/TodoController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ToDoApplication.DataAccess;
using ToDoApplication.Models;

namespace ToDoApplication.Controllers
{
    public class TodoController : Controller
    {
        private TodoRepository repository;

        public TodoController()
        {
            repository = new TodoRepository(ConfigurationManager.ConnectionStrings["ToDoApp"].ToString());
        }
        //
        // GET: /Todo/
        public ActionResult Index(int categoryId)
        {
            List<Todo> model = repository.GetByCategoryId(categoryId);

            return View(model);
        }

        public ActionResult Create(int categoryId)
        {
            Todo todo = new Todo();
            todo.CategoryId = categoryId;

            return View(todo);
        }

        [HttpPost]
        public ActionResult Create(Todo todo)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            repository.Insert(todo);
            return RedirectToAction("Index", new { categoryId = todo.CategoryId});
        }
	}
}

ToDoApplication/ToDoApplication/Views/Category/Create.cshtml
@model ToDoApplication.ViewModels.Category.CategoryCreateViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Category</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name)
                @Html.ValidationMessageFor(model => model.Name)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ToDoApplication/ToDoApplication/Views/Category/Edit.cshtml
@model ToDoApplication.ViewModels.Category.CategoryEditViewModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Category</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name)
                @Html.ValidationMessageFor(model => model.Name)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ToDoApplication/ToDoApplication/Views/Category/Index.cshtml
@model ToDoApplication.ViewModels.Category.CategoryIndexViewModel

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>
<h2>@Model.CurrentDateTime.ToString("yyyy-MM-dd HH:mm:ss")</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            Name
        </th>
        <th></th>
    </tr>

@foreach (var item in Model.Categories) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", 
            new { id = item.Id }, 
            new {onclick = "return confirm('Are you sure you want to delete this category?');"})|
            @Html.ActionLink("Todos", "Index", "Todo", new { categoryId = item.Id }, null)
        </td>
    </tr>
}

</table>

ToDoApplication/ToDoApplication/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

ToDoApplication/ToDoApplication/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

ToDoApplication/ToDoApplication/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="http://asp.net" class="btn btn-primary btn-large">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

ToDoApplication/ToDoApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - To Do Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("To Do Application", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Categories", "Index", "Category")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - To Do Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

ToDoApplication/ToDoApplication/Views/Todo/Create.cshtml
@model ToDoApplication.Models.Todo

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Todo</h4>
        <hr />
        @Html.ValidationSummary(true)

        @Html.HiddenFor(model => model.CategoryId)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title)
                @Html.ValidationMessageFor(model => model.Title)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsDone, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IsDone)
                @Html.ValidationMessageFor(model => model.IsDone)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ToDoApplication/ToDoApplication/Views/Todo/Index.cshtml
@model IEnumerable<ToDoApplication.Models.Todo>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create", new {categoryId = Model.First().CategoryId})
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsDone)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IsDone)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>